INFO:aiogram:Bot: CoinLuck Game üçÄ [@coinluck_bot]
INFO:aiogram.dispatcher.dispatcher:Start polling.
INFO:root:change 48694 > 352 and 150 userid: 1737649749
INFO:root:1737649749 bought üçì 1000
INFO:root:1737649749 bought üçå 100000
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-250' coro=<Dispatcher._process_polling_updates() done, defined at /home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py:409> exception=MessageIsTooLong('Message is too long')>
Traceback (most recent call last):
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 417, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 238, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 259, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/nail/oir/main.py", line 372, in upt
    await message.answer(temps.err(message))
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/types/message.py", line 359, in answer
    return await self.bot.send_message(
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/bot/bot.py", line 314, in send_message
    result = await self.request(api.Methods.SEND_MESSAGE, payload)
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/bot/base.py", line 208, in request
    return await api.make_request(self.session, self.server, self.__token, method, data, files,
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/bot/api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.MessageIsTooLong: Message is too long
